### ISSUE TITLE
AppCenter vs download arrow

### ISSUE THREAD

**Issue by eyelash** [elementary/icons#98] opened 2016-08-06 15:27 UTC
The download icon on the website and the AppCenter icon are visually quite similar but the arrow shape is different:
![download](https://elementary.io/images/developer/save.svg)
![AppCenter](http://beta.elementary.io/branch/origin/loki/images/icons/128/system-software-install.svg)
I like the first shape much better and would like to see it also on the AppCenter icon.

**Comment by snwh** [comment] 2016-08-06 16:04
There's a new icon for AppCentre coming, this one is just a placeholder. :wink:

**Comment by Guard13007** [comment] 2016-08-09 05:48
@snwh Any chance of a preview?

**Comment by snwh** [comment] 2016-08-09 13:34
@Guard13007 https://github.com/elementary/icons/pull/83

**Comment by Guard13007** [comment] 2016-08-09 16:52
Hmm... not sure what I think about it. It feels kind of childish to me. Then again, maybe it looks better viewed in its proper setting. Something about the round-ness of it all just seems too childish. I feel like it could be sharper while still looking clean.

**Comment by danrabbit** [comment] 2016-08-24 22:30
Closing this issue as a duplicate of #83

**Closed by danrabbit** 2016-08-24 22:30 UTC
