### ISSUE TITLE
automatic install script missing

### ISSUE THREAD

**Issue by decathorpe** [elementary/icons#145] opened 2016-11-07 20:01 UTC
A small script installing the icon theme for the current user (to `$HOME/.local/share/icons/` or system-wide (to `/usr/share/icons/`) would be appreciated, so no manual copying of the files and folders has to be done. 

For example, the Paper icon theme by @snwh seems to have something using autoconf+automake that does the job, although CMake might be preferrable for elementary (maybe in conjunction with a resolution to https://github.com/elementary/icons/issues/39 ?).

**Comment by danrabbit** [comment] 2016-11-07 22:52
I think this is a duplicate of #39 since a build system would presumably handle installation

**Closed by danrabbit** 2016-11-07 22:52 UTC
