### ISSUE TITLE
Drag-and-drop should use action icons with better visibility

### ISSUE THREAD

**Issue by hanaral** [elementary/icons#986] opened 2021-01-02 17:14 UTC
## What Happened
The drag-and-drop cursor icons are miniscule when speaking in terms of their realive size to other UI elements and in terms of the size we see them as from typical viewing angles.

Example using the 'move' DnD icon | Example using the 'add' DnD icon
------------ | -------------
![2021-01-15 12 03 54](https://user-images.githubusercontent.com/58219504/104809561-26cd1080-57e6-11eb-8e86-4f7461694fb2.jpg) | ![IMG_0637](https://user-images.githubusercontent.com/58219504/104809203-6e05d200-57e3-11eb-84de-4c31a8223a17.jpg)
![cursor1](https://user-images.githubusercontent.com/58219504/104809691-f5087980-57e6-11eb-91d7-da7448d791ec.png) | ![cursor2](https://user-images.githubusercontent.com/58219504/104809695-fafe5a80-57e6-11eb-9a33-1433e392ff36.png)

## Expected Behavior
A larger emblem is used on the cursor, there are plenty of preexisting colourful and contrasty icons from  elementary's own set. 

## Steps to Reproduce

Initiate a drag and try to tell what the action is purely by it's shape and colour from a typical viewing distance.

## Platform Information
elementary OS 6 Daily

**Comment by danrabbit** [comment] 2021-01-15 01:20
Can you elaborate on this? What apps are you dragging from? Can you provide a screenshot? I'm not able to reproduce an issue with the given information

**Comment by hanaral** [comment] 2021-01-15 12:39
> Can you elaborate on this? What apps are you dragging from? Can you provide a screenshot? I'm not able to reproduce an issue with the given information

Apologies, I've updated it with screenshots

**Comment by danirabbit** [comment] 2024-04-22 17:24
Fixed in #1250

**Closed by danirabbit** 2024-04-22 17:24 UTC
Labels: Needs Design
