### ISSUE TITLE
Odin Dark Theme: WiFi Disconnected Icon not Legible

### ISSUE THREAD

**Issue by candiedoperation** [elementary/icons#1028] opened 2021-05-05 03:09 UTC
## What Happened

On WiFi Disconnection, the notification which pops up in dark mode has an illegible WiFi Icon

## Expected Behavior

Like the icon in light mode, the WiFi Disconnected Icon in dark mode is expected to be legible

## Steps to Reproduce

1. Switch to Dark Mode
2. Turn Wireless off from wingpanel
3. The notification will have an illegible icon
![Screenshot from 2021-05-05 08-26-27](https://user-images.githubusercontent.com/47198395/117092935-39f7f200-ad7d-11eb-9c8d-88395c800194.png)

### Logs

None

## Platform Information

Operating System: elementary OS 6
Edition: (Public Beta)
Hardware Information:
- Quad-Core Intel® Core™ i5-8250U CPU @ 1.60GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 7.7 GiB memory
- 467.2 GB storage (SSD)

Laptop Information: HP Pavilion x360

**Comment by danrabbit** [comment] 2021-05-19 01:57
Closing as a duplicate of https://github.com/elementary/icons/issues/1002

**Closed by danrabbit** 2021-05-19 01:57 UTC
