### ISSUE TITLE
folder-music doesn't look good with dark style

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#952] opened 2020-09-11 19:52 UTC
Similar to #951 

![Screenshot from 2020-09-11 13-48-25](https://user-images.githubusercontent.com/611168/92967148-fc350a80-f435-11ea-931a-83b89fc5d23a.png)

![Screenshot from 2020-09-11 13-52-01](https://user-images.githubusercontent.com/611168/92967163-ff2ffb00-f435-11ea-8855-52b325f60ed9.png)

**Comment by danrabbit** [comment] 2020-10-05 22:52
Turns out this is a duplicate of #853

**Closed by danrabbit** 2020-10-05 22:52 UTC
